#!/bin/bash




count=0
public_ip=$(curl --no-progress-meter ifconfig.me)
local_ip=$(ip address show | awk '/inet/' | awk 'NR==3 {print $2}')
memtotal=$(cat /proc/meminfo | awk 'tolower($0) ~ /memtotal/' | awk '{print $2 / 1024 / 1024}')

while [[ true ]]; do
	count=$(expr $count + 1)
	local_ip=$(ip address show | awk '/inet/' | awk 'NR==3 {print $2}')
	memfree=$(cat /proc/meminfo | awk 'tolower($0) ~ /memfree/' | awk '{print $2/1024/1024}')
	memused=$(echo $memtotal $memfree | awk '{print (($1-$2)/$1)*100}' | awk '{split($1,a,"."); print a[1]}')
	bat_status=$(cat /sys/class/power_supply/BAT0/status)
	battery=$(cat /sys/class/power_supply/BAT0/capacity)
	if [[ $(($count%5)) -eq 0 ]]; then
		local_ip=$(ip address show | awk '/inet/' | awk 'NR==3 {print $2}')
	fi
	if [[ count -gt 600 ]]; then
		public_ip=$(curl ifconfig.me)
		count=0
	fi
	date=$(date)
	if [[ -z "$local_ip" ]]; then
		echo "$battery% $bat_status | RAM $memused% | No Internet | $date "
	else
		echo "[ $battery% $bat_status ] [ RAM $memused% ] [ IPv4 - $local_ip ] [ PublicIP - $public_ip ] [ $date ] "
	fi
	sleep 1
done
